package simulation;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Shania Dicen
 */
public class SimulationPrelims extends SimulationGUI {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        new NumberOfCustomers().setVisible(true);
    }
}

class NumberOfCustomers extends javax.swing.JFrame {

    private int customers;
    private Replication r1;
    private ArrayList<ReplicationCustomer> r1Log;
    private Replication r2;
    private ArrayList<ReplicationCustomer> r2Log;
    private Replication r3;
    private ArrayList<ReplicationCustomer> r3Log;
    private Replication r4;
    private ArrayList<ReplicationCustomer> r4Log;
    private Replication r5;
    private ArrayList<ReplicationCustomer> r5Log;

    /**
     * Creates new form SimulationPrelims
     */
    public NumberOfCustomers() {
        try {
            GraphicsEnvironment ge
                    = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Font/Arial Narrow Bold.ttf")));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Font/Arial Narrow.ttf")));
        } catch (IOException | FontFormatException e) {
            //Handle exception
        }
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgopen = new javax.swing.JPanel();
        howManyCustomers = new javax.swing.JLabel();
        numberOfCustomers = new javax.swing.JTextField();
        beginButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bgopen.setBackground(new java.awt.Color(255, 159, 67));
        bgopen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        howManyCustomers.setBackground(new java.awt.Color(255, 255, 255));
        howManyCustomers.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        howManyCustomers.setForeground(new java.awt.Color(255, 255, 255));
        howManyCustomers.setText("HOW MANY CUSTOMERS?");
        bgopen.add(howManyCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        numberOfCustomers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numberOfCustomers.setToolTipText("enter the number of customers to simulate");
        numberOfCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfCustomersActionPerformed(evt);
            }
        });
        bgopen.add(numberOfCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, 30));

        beginButton.setBackground(new java.awt.Color(254, 202, 87));
        beginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beginButtonMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIMULATE");

        javax.swing.GroupLayout beginButtonLayout = new javax.swing.GroupLayout(beginButton);
        beginButton.setLayout(beginButtonLayout);
        beginButtonLayout.setHorizontalGroup(
            beginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beginButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
        beginButtonLayout.setVerticalGroup(
            beginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bgopen.add(beginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 80, 30));

        close.setFont(new java.awt.Font("Arial Narrow", 0, 22)); // NOI18N
        close.setForeground(new java.awt.Color(255, 227, 166));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        bgopen.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 30, 30));

        jPanel1.setBackground(new java.awt.Color(255, 159, 67));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust1.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust1.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust2.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust2.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust1.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulation/images/cust2.png"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(1, 1, 1)
                    .addComponent(jLabel5)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel3)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel6)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel7)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bgopen.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgopen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgopen, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfCustomersActionPerformed
        // TODO add your handling code here:
//         customers = getNoCust();
    }//GEN-LAST:event_numberOfCustomersActionPerformed

    private void beginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginButtonMousePressed
        // TODO add your handling code here:
        customers = getNoCust();
    }//GEN-LAST:event_beginButtonMousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit?", "Exit Program",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);
        }

    }//GEN-LAST:event_closeMousePressed

    public int getNumCust() {
        return customers;
    }

    public int getNoCust() {
        try {

            customers = Integer.parseInt(numberOfCustomers.getText());
            this.setVisible(false);
            r1 = new Replication(customers);
            r1Log = new ArrayList<ReplicationCustomer>();
            r2 = new Replication(customers);
            r2Log = new ArrayList<ReplicationCustomer>();
            r3 = new Replication(customers);
            r3Log = new ArrayList<ReplicationCustomer>();
            r4 = new Replication(customers);
            r4Log = new ArrayList<ReplicationCustomer>();
            r5 = new Replication(customers);
            r5Log = new ArrayList<ReplicationCustomer>();
            System.out.print("Number of Customers: " + customers);
            new SimulationGUI(customers, r1, r1Log, r2, r2Log, r3, r3Log, r4, r4Log, r5, r5Log).setVisible(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Kindly enter a number!");
        }
        return customers;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beginButton;
    private javax.swing.JPanel bgopen;
    private javax.swing.JLabel close;
    private javax.swing.JLabel howManyCustomers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberOfCustomers;
    // End of variables declaration//GEN-END:variables

}
